# Generated by Django 5.2.11 on 2026-03-31 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('te', 'Telugu'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('or', 'Odia'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('as', 'Assamese'), ('mai', 'Maithili'), ('sat', 'Santali'), ('kas', 'Kashmiri'), ('ne', 'Nepali'), ('kok', 'Konkani'), ('sd', 'Sindhi'), ('doi', 'Dogri'), ('mni', 'Manipuri'), ('brx', 'Bodo'), ('sa', 'Sanskrit'), ('bh', 'Bhojpuri'), ('mag', 'Magahi'), ('awa', 'Awadhi'), ('raj', 'Rajasthani'), ('chg', 'Chhattisgarhi'), ('bgc', 'Haryanvi'), ('mwr', 'Marwari'), ('en', 'English'), ('zh', 'Mandarin Chinese'), ('es', 'Spanish'), ('ar', 'Arabic'), ('fr', 'French'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('de', 'German'), ('ja', 'Japanese'), ('ko', 'Korean'), ('it', 'Italian'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('nl', 'Dutch'), ('th', 'Thai'), ('sv', 'Swedish'), ('fil', 'Filipino'), ('id', 'Indonesian')], default='en', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
